language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - TESTS=false
        - PACKAGE="ocaml-freestanding"
        - POST_INSTALL_HOOK="./.travis-test-mirage.sh"
    matrix:
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-hvt" MIRAGE_TEST_MODE="hvt"
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-virtio" MIRAGE_TEST_MODE="virtio"
        - OCAML_VERSION=4.09 EXTRA_DEPS="solo5-bindings-muen" MIRAGE_TEST_MODE="muen"
        - OCAML_VERSION=4.08 EXTRA_DEPS="solo5-bindings-hvt" MIRAGE_TEST_MODE="hvt"
        - OCAML_VERSION=4.08 EXTRA_DEPS="solo5-bindings-virtio" MIRAGE_TEST_MODE="virtio"
        - OCAML_VERSION=4.08 EXTRA_DEPS="solo5-bindings-muen" MIRAGE_TEST_MODE="muen"
        - OCAML_VERSION=4.07 EXTRA_DEPS="solo5-bindings-hvt" MIRAGE_TEST_MODE="hvt"
        - OCAML_VERSION=4.07 EXTRA_DEPS="solo5-bindings-virtio" MIRAGE_TEST_MODE="virtio"
        - OCAML_VERSION=4.07 EXTRA_DEPS="solo5-bindings-muen" MIRAGE_TEST_MODE="muen"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-bindings-hvt" MIRAGE_TEST_MODE="hvt"
        - OCAML_VERSION=4.06 INSTALL_LOCAL=1 EXTRA_DEPS="solo5-bindings-virtio" MIRAGE_TEST_MODE="virtio"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-bindings-muen" MIRAGE_TEST_MODE="muen"
