language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - EXTRA_REMOTES="https://github.com/mirage/mirage-dev.git"
        - TESTS=false
    matrix:
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-kernel-ukvm"
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-kernel-virtio"
        - OCAML_VERSION=4.03 EXTRA_DEPS="solo5-kernel-ukvm"
        - OCAML_VERSION=4.03 EXTRA_DEPS="solo5-kernel-virtio"
        - OCAML_VERSION=4.02 EXTRA_DEPS="solo5-kernel-ukvm"
        - OCAML_VERSION=4.02 EXTRA_DEPS="solo5-kernel-virtio"
