language: c
sudo: required
dist: trusty
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
    global:
        - TESTS=false
        - PACKAGE="ocaml-freestanding"
        - OPAM_VERSION=1.2.2
    matrix:
        - OCAML_VERSION=4.07 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.07 EXTRA_DEPS="solo5-bindings-virtio"
        - OCAML_VERSION=4.07 EXTRA_DEPS="solo5-bindings-muen"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-bindings-virtio"
        - OCAML_VERSION=4.06 EXTRA_DEPS="solo5-bindings-muen"
        - OCAML_VERSION=4.05 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.05 EXTRA_DEPS="solo5-bindings-virtio"
        - OCAML_VERSION=4.05 EXTRA_DEPS="solo5-bindings-muen"
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-bindings-hvt"
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-bindings-virtio"
        - OCAML_VERSION=4.04 EXTRA_DEPS="solo5-bindings-muen"
